[auto_bencher]
jar_dir = "merge"
server_count = "4" # without the sequencer
server_client_ratio = "1.0" # client / server
max_server_per_machine = "1"
max_client_per_machine = "2"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "1572864" # 6GB
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "4"
"org.vanilladb.bench.BenchmarkerParameters.WARM_UP_INTERVAL" = "0"
#"org.vanilladb.bench.BenchmarkerParameters.BENCHMARK_INTERVAL" = "1200000"
"org.vanilladb.bench.BenchmarkerParameters.BENCHMARK_INTERVAL" = "900000"
"org.vanilladb.bench.BenchmarkerParameters.RTE_SLEEP_TIME" = "0"
"org.vanilladb.bench.BenchmarkerParameters.NUM_RTES" = "200"
"org.vanilladb.bench.StatisticMgr.GRANULARITY" = "10000"

[elasql]
"org.elasql.server.Elasql.SERVICE_TYPE" = "3"
"org.elasql.remote.groupcomm.client.BatchSpcSender.COMM_BATCH_SIZE" = "20"
"org.elasql.storage.tx.recovery.DdRecoveryMgr.DISABLE_STORAGE_LOGGING" = "true"
# T-Part & Hermes
"org.elasql.schedule.tpart.TPartScheduler.SCHEDULE_BATCH_SIZE" = "200"
# T-Part
"org.elasql.schedule.tpart.CostAwareNodeInserter.BETA" = "0.8"
# Hermes
"org.elasql.schedule.tpart.hermes.FusionTable.EXPECTED_MAX_SIZE" = "10000000"
"org.elasql.schedule.tpart.hermes.HermesNodeInserter.IMBALANCED_TOLERANCE" = "0.1"

[elasqlbench]
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.DATABASE_MODE" = "1" # Single Table
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.WORKLOAD_TYPE" = "3" # Multi-tenants
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.INIT_RECORD_PER_PART" = "10000000"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.RW_TX_RATE" = "0.5"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.TX_RECORD_COUNT" = "2"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.ADD_INSERT_IN_WRITE_TX" = "0"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.ZIPFIAN_PARAMETER" = "0.99"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.TENANTS_PER_PART" = "4"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.ENABLE_HOTSPOT" = "true"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.HOTSPOT_HOTNESS" = "0.9"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.HOTSPOT_CHANGE_PERIOD" = "600"

