[auto_bencher]
jar_dir = "hermes"
server_count = "4" # without the sequencer
server_client_ratio = "1.0" # client / server
max_server_per_machine = "1"
max_client_per_machine = "3"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "1572864" # 6GB
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "4"

[elasql]
"org.elasql.server.Elasql.SERVICE_TYPE" = "1"
"org.elasql.remote.groupcomm.client.BatchSpcSender.COMM_BATCH_SIZE" = "1"

[elasqlbench]
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.DATABASE_MODE" = "1"
"org.elasql.bench.benchmarks.ycsb.ElasqlYcsbConstants.INIT_RECORD_PER_PART" = "10000000"
