[auto_bencher]
jar_dir = "test"
server_count = "1 2 3" # without the sequencer
server_client_ratio = "1.0" # client / server
max_server_per_machine = "1"
max_client_per_machine = "3"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "1572864" # 6GB
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "2"
"org.vanilladb.bench.BenchmarkerParameters.WARM_UP_INTERVAL" = "30000"
"org.vanilladb.bench.BenchmarkerParameters.BENCHMARK_INTERVAL" = "60000"
"org.vanilladb.bench.StatisticMgr.GRANULARITY" = "3000"
"org.vanilladb.bench.BenchmarkerParameters.NUM_RTES" = "50"

[elasql]
"org.elasql.server.Elasql.SERVICE_TYPE" = "1 2"
"org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE" = "20"

"org.elasql.schedule.tpart.TPartPartitioner.NUM_TASK_PER_SINK" = "20"
"org.elasql.schedule.tpart.CostAwareNodeInserter.BETA" = "0.8"

[elasqlbench]
# TPC-C
"org.elasql.bench.benchmarks.tpcc.ElasqlTpccConstants.WAREHOUSE_PER_PART" = "5"
