
[auto_bencher]
jar_dir = "test"
server_count = "3" # without the sequencer
server_client_ratio = "1" # client / server
max_server_per_machine = "1"
max_client_per_machine = "2"

[vanilladb]
"org.vanilladb.core.storage.buffer.BufferMgr.BUFFER_POOL_SIZE" = "1572864" # 4GB
"org.vanilladb.core.storage.file.io.IoAllocator.USE_O_DIRECT" = "true"

[vanillabench]
"org.vanilladb.bench.BenchmarkerParameters.BENCH_TYPE" = "2"

[elasql]
"org.elasql.server.Elasql.SERVICE_TYPE" = "1"
"org.elasql.remote.groupcomm.client.BatchSpcSender.BATCH_SIZE" = "1"

[elasqlbench]
"org.elasql.bench.benchmarks.tpcc.ElasqlTpccConstants.WAREHOUSE_PER_PART" = "5"
