# ===== General =====
# Number of Servers (<= CONFIG_LOADING_NUM_OF_SERVERS)
PARAM_NUM_OF_SERVERS="3"

# ===== VanillaDB =====
# The Size of The Buffer Pool
PARAM_DB_BUFFER_POOL_SIZE="1500000"
# The Size of The Thread Pool
PARAM_DB_THREAD_POOL_SIZE="1000"

# ===== ElaSQL =====
# Server Type (0: Fully-replicated, 1: Calvin, 2: T-Part)
PARAM_DDDB_SERVER_TYPE="1"
# Batch Size
PARAM_DDDB_BATCH_SIZE="20"

# ===== ElaSQL: T-Part =====
# Sink Size
PARAM_TPART_SINK_SIZE="100"
# Beta
PARAM_TPART_BETA="0.85"
#"0.835 0.8375 0.84 0.8475 0.845"
# Enabling Reorder (0=false, 1=true)
PARAM_TPART_REORDER="0"
# Enabling Replication (0=false, 1=true)
PARAM_TPART_REPLICATION="0"
# Replication Limit
PARAM_TPART_REPLICATION_LIMIT="0"

# ===== Benchmarker =====
# Benchmarker Type (1: Micro-benchmark, 2: TPC-C, 3: TPC-E)
PARAM_BENCH_TYPE="2"
# Number of RTEs
PARAM_BENCH_NUM_OF_RTES="200"
# Time for warming up (in m.s.)
PARAM_BENCH_WARMUP_TIME="1"
# Time for benchmarking (in m.s.)
PARAM_BENCH_BENCH_TIME="500000"

# ===== Micro-benchmark =====
# Distributed Tx Rate
PARAM_MICRO_DIST_TX_RATE="0.1"
# Read-Write Tx Rate
PARAM_MICRO_RW_TX_RATE="0.5"
# Skew Tx Rate
PARAM_MICRO_SKEW_TX_RATE="0.0"
# Long-Read Tx Rate
PARAM_MICRO_LONG_READ_TX_RATE="0.0"
# Total Read Count
PARAM_MICRO_TOTAL_READ_COUNT="10"
# Local Hot Count
PARAM_MICRO_LOCAL_HOT_COUNT="1"
# Remote Hot Count
PARAM_MICRO_REMOTE_HOT_COUNT="0"
# Remote Cold Count
PARAM_MICRO_REMOTE_COLD_COUNT="5"
# Write Ratio in RW Txs
PARAM_MICRO_WRITE_RATIO_IN_RW_TX="0.5"
# Hot Conflict Rate
PARAM_MICRO_HOT_CONFLICT_RATE="0.01"
# Skew Precentage
PARAM_MICRO_SKEW_PERCENTAGE="0.2"

# ===== TPC-E =====
# Trade Percentage
PARAM_TPCE_TRADE_PERCENTAGE="0.5"
