name: autobench tests
on: 
  push:
    paths-ignore:
      - 'README.md'
jobs:
  style-check-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run eslint
      - run: npm run test
